from desafio_arvore_b.arvore_b import *

construir_lista_nos = lambda *args: list(Node(i) for i in args)
pagina = Page(lista_nos=construir_lista_nos(29))
pagina.lista_nos[0].left = Page(4, lista_nos=construir_lista_nos(8, 15))
pagina.lista_nos[0].right = Page(4, lista_nos=construir_lista_nos(37, 45, 60))
pagina.lista_nos[0].left.lista_nos[0].left = Page(4, lista_nos=construir_lista_nos(1, 3, 4, 7))
pagina.lista_nos[0].left.lista_nos[1].left = Page(4, lista_nos=construir_lista_nos(10, 12, 13, 14))
pagina.lista_nos[0].left.lista_nos[1].right = Page(4, lista_nos=construir_lista_nos(18, 20, 25))
pagina.lista_nos[0].right.lista_nos[0].left = Page(4, lista_nos=construir_lista_nos(30, 36))
pagina.lista_nos[0].right.lista_nos[1].left = Page(4, lista_nos=construir_lista_nos(40, 41, 42, 43))
pagina.lista_nos[0].right.lista_nos[2].left = Page(4, lista_nos=construir_lista_nos(51, 52))
pagina.lista_nos[0].right.lista_nos[2].right = Page(4, lista_nos=construir_lista_nos(70, 77, 83))
arvore_b = Arvore_b(pagina)
arvore_b.inserir_elemento(11)
arvore_b.inserir_elemento(19)
arvore_b.inserir_elemento(2)
print('Pesquisa do 11 =', arvore_b.elemento_na_arvore(11))
print('Pesquisa do 2 =', arvore_b.elemento_na_arvore(2))
print('Pesquisa do 19 =', arvore_b.elemento_na_arvore(19))
